name: globant

services:
    postgres:
        image: postgres:16.4
        container_name: database
        env_file:
            - ./.env
        volumes:
            - ${POSTGRES_DATA_PATH:-./.postgres-data}:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
            interval: 5s
            timeout: 5s
            retries: 5
    backend:
        build:
            context: .
        container_name: fastapi_app
        ports:
            - ${BACKEND_PORT:-8080}:8000
        env_file:
            - ./.env
        environment:
            - ENVIRONMENT=${ENV:-local}
        restart: on-failure
        develop:
            watch:
                - action: sync+restart
                  path: ./app
                  target: /api/app
                - action: rebuild
                  path: pyproject.toml
                  target: /api/pyproject.toml
        depends_on:
            postgres:
                condition: service_healthy
