name: globant

volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${POSTGRES_DATA_PATH:-./.postgres-data}

services:
    postgres:
        image: postgres:16.4
        container_name: database
        env_file:
            - ./.env
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT:-5432}:5432
    backend:
        build:
            context: .
        container_name: fastapi_app
        ports:
            - ${BACKEND_PORT:-8080}:8000
        env_file:
            - ./.env
        environment:
            - ENVIRONMENT=${ENV:-local}
        restart: on-failure
        develop:
            watch:
                - action: sync+restart
                  path: ./app
                  target: /api/app
                - action: rebuild
                  path: pyproject.toml
                  target: /api/pyproject.toml
        depends_on:
            - postgres
